<?php

/**
 * @file
 * Video filter is a highly flexible and easy extendable filter module to embed
 * any type of video in your site using a simple tag.
 */

module_load_include('inc', 'video_filter', 'video_filter.codecs');

/**
 * Implements hook_filter_info().
 */
function video_filter_filter_info() {
  $filters = array();
  $filters['video_filter'] = array(
    'title' => t('Video Filter'),
    'description' => t('Substitutes [video:URL] with embedded HTML.'),
    'process callback' => '_video_filter_process',
    'settings callback' => '_video_filter_settings',
    'default settings' => array(
      'video_filter_width' => '400',
      'video_filter_height' => '400',
    ),
    'tips callback' => '_video_filter_tips',
    // See http://drupal.org/node/1061244.
    'weight' => -1,
  );
  return $filters;
}

function _video_filter_settings($form, &$form_state, $filter, $format, $defaults, $filters) {

  $settings['video_filter_width'] = array(
    '#type' => 'textfield',
    '#title' => t('Default width setting'),
    '#default_value' => isset($filter->settings['video_filter_width']) ? $filter->settings['video_filter_width'] : $defaults['video_filter_width'],
    '#maxlength' => 4,
  );
  $settings['video_filter_height'] = array(
    '#type' => 'textfield',
    '#title' => t('Default height setting'),
    '#default_value' => isset($filter->settings['video_filter_height']) ? $filter->settings['video_filter_height'] : $defaults['video_filter_height'],
    '#maxlength' => 4,
  );
  return $settings;
}

function _video_filter_tips($filter, $format, $long = FALSE) {
  if ($long) {
    $codecs = video_filter_get_codec_info();
    $supported = array();
    $instructions = array();
    foreach ($codecs as $codec) {
      $supported[] = $codec['name'];
      $instructions[] = isset($codec['instructions']) ? '<li>' . $codec['name'] . ':<br/>' . $codec['instructions'] . '</li>' : '';
    }
    return t('
      <p><strong>Video Filter</strong></p>
      <p>You may insert videos from popular video sites by using a simple tag <code>[video:URL]</code>.</p>
      <p>Examples:</p>
      <ul>
        <li>Single video:<br /><code>[video:http://www.youtube.com/watch?v=uN1qUeId]</code></li>
        <li>Override default width and height:<br /><code>[video:http://www.youtube.com/watch?v=uN1qUeId width:X height:Y]</code></li>
        <li>Align the video:<br /><code>[video:http://www.youtube.com/watch?v=uN1qUeId align:right]</code></li>
      </ul>
      <p>Supported sites: @codecs.</p>
      <p>Special instructions:</p>
      <small>Some codecs need special input. You\'ll find those instructions here.</small>
      <ul>!instructions</ul>', array(
        '@codecs' => implode(', ', $supported),
        '!instructions' => implode('', $instructions),
      )
    );
  }
  else {
    return t('You may insert videos with [video:URL]');
  }
}

function _video_filter_process($text, $filter, $format, $langcode, $cache, $cache_id) {
  if (preg_match_all('/\[video(\:(.+))?( .+)?\]/isU', $text, $matches_code)) {
    foreach ($matches_code[0] as $ci => $code) {
      $video = array(
        'source' => $matches_code[2][$ci],
      );

      $video['source'] = _getSwf($video['source']);

      if ($matches_code[3][$ci] && preg_match_all('/\s+([a-zA-Z_]+)\:(\s+)?([0-9a-zA-Z\/]+)/i', $matches_code[3][$ci], $matches_attributes)) {
        foreach ($matches_attributes[0] as $ai => $attribute) {
          $video[$matches_attributes[1][$ai]] = $matches_attributes[3][$ai];
        }
      }

      $ratio = 1;

      if (isset($video['ratio']) && preg_match('/(\d+)\/(\d+)/', $video['ratio'], $tratio)) {
        // Validate given ratio parameter.
        $ratio = $tratio[1] / $tratio[2];
      }

      // First, check if user has set a width.
      if (isset($video['width']) && !isset($video['height'])) {
        $video['height'] = $filter->settings['video_filter_height'];
      }
      // Else, if user has set height.
      elseif (isset($video['height']) && !isset($video['width'])) {
        $video['width'] = $video['height'] * $ratio;
      }
      // Maybe both?
      elseif (isset($video['height']) && isset($video['width'])) {
        $video['width'] = $video['width'];
        $video['height'] = $video['height'];
      }
      // Fall back to defaults.
      elseif (!isset($video['height']) && !isset($video['width'])) {
        $video['width'] = $filter->settings['video_filter_width'] != '' ? $filter->settings['video_filter_width'] : 400;
        $video['height'] = $filter->settings['video_filter_height'] != '' ? $filter->settings['video_filter_height'] : 400;
      }

      // Default value for control bar height.
      $control_bar_height = 0;
      if (isset($video['control_bar_height'])) {
        // Respect control_bar_height option if present.
        $control_bar_height = $video['control_bar_height'];
      }

      // Resize to fit within width and height repecting aspect ratio.
      if ($ratio) {
        $scale_factor = min(array(
          ($video['height'] - $control_bar_height),
          $video['width'] / $ratio,
        ));
        $video['height'] = round($scale_factor + $control_bar_height);
        $video['width'] = round($scale_factor * $ratio);
      }

      $video['align'] = (isset($video['align']) && in_array($video['align'], array(
        'left',
        'right',
        'center',
      ))) ? $video['align'] : NULL;

      // Let modules have final say on video parameters.
      drupal_alter('video_filter_video', $video);

      $replacement = video_filter_flash($video);

      $text = str_replace($code, $replacement, $text);
    }
  }
  return $text;
}

/**
 * Wrapper that calls the theme function.
 */
function video_filter_flash($video, $params = array()) {
  return theme('video_filter_flash', array('video' => $video, 'params' => $params));
}

function video_filter_get_codec_info() {
  static $codecs;
  if (!isset($codecs)) {
    $codecs = module_invoke_all('codec_info');
    drupal_alter('video_filter_codec_info', $codecs);
  }
  return $codecs;
}

/**
 * Function that outputs the <object> element.
 *
 * @ingroup themeable
 */
function theme_video_filter_flash($variables) {
  $output = '';

  $video = $variables['video'];
  $params = isset($variables['params']) ? $variables['params'] : array();

  $output .= '<object type="application/x-shockwave-flash" ';

  $output .= 'width="' . $video['width'] . '" height="' . $video['height'] . '" data="' . $video['source'] . '">' . "\n";

  $defaults = array(
    'movie' => $video['source'],
    'wmode' => 'transparent',
    'allowFullScreen' => 'true',
  );

  $params = array_merge($defaults, (is_array($params) && count($params)) ? $params : array());

  foreach ($params as $name => $value) {
    $output .= '  <param name="' . $name . '" value="' . $value . '" />' . "\n";
  }

  $output .= '</object>' . "\n";

  return $output;
}

/**
 * Implements hook_theme().
 */
function video_filter_theme($existing, $type, $theme, $path) {
  return array(
    'video_filter_flash' => array(
      'variables' => array('video' => NULL, 'params' => NULL),
    ),
    'video_filter_dashboard' => array(
      'variables' => array('form' => NULL),
      'template' => 'video_filter_dashboard',
    ),
  );
}

/**
 * Implements hook_menu().
 */
function video_filter_menu() {
  $items = array();

  $items['video_filter/dashboard/%'] = array(
    'title' => 'Videofilter',
    'description' => 'Dashboard',
    'page callback' => 'video_filter_dashboard_page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'page arguments' => array(2),
    'theme callback' => '_video_filter_dashboard_theme',
  );

  return $items;
}

/**
 * Return the theme name to be used when showing linkit dashboard
 */
function _video_filter_dashboard_theme() {
  return variable_get('admin_theme', 'seven');
}

/**
 * Template preprocess function for video_filter_dashboard().
 */
function template_preprocess_video_filter_dashboard(&$variables) {
  // Construct page title.
  $variables['head_title']    = t('Video filter dashboard');
  $variables['head']          = drupal_get_html_head();
  $variables['help']          = theme('help');
  $variables['language']      = $GLOBALS['language'];
  $variables['language']->dir = $GLOBALS['language']->direction ? 'rtl' : 'ltr';
  $variables['messages']      = isset($variables['show_messages']) ? theme('status_messages') : '';
  $variables['css']           = drupal_add_css();
  $variables['styles']        = drupal_get_css();
  $variables['scripts']       = drupal_get_js();
}

/**
 * Creates the dashboard.
 */
function video_filter_dashboard_page($editor) {
  module_invoke('admin_menu', 'suppress');
  // Add CSS.
  drupal_add_css(drupal_get_path('module', 'video_filter') . '/css/video_filter.css');

  switch ($editor) {
    case 'wysiwyg_tinymce':
      // Add JavaScript.
      drupal_add_js(wysiwyg_get_path('tinymce') . '/jscripts/tiny_mce/tiny_mce_popup.js');
      drupal_add_js(drupal_get_path('module', 'video_filter') . '/editors/tinymce/video_filter.js');
      break;

    case 'ckeditor':
    case 'wysiwyg_ckeditor':
      // Add JavaScript.
      drupal_add_js(drupal_get_path('module', 'video_filter') . '/editors/ckeditor/video_filter_dialog.js');
      break;

    case 'fckeditor':
    case 'wysiwyg_fckeditor':
      // Add JavaScript.
      drupal_add_js(drupal_get_path('module', 'video_filter') . '/editors/fckeditor/video_filter/video_filter_dialog.js');
      break;
  }

  print theme('video_filter_dashboard', array('form' => render(drupal_get_form('_video_filter_form'))));
  exit();
}

function _video_filter_form() {
  $form['video_filter'] = array(
    '#type' => 'fieldset',
    '#title' => t('Insert Video'),
    '#weight' => 0,
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
    '#attributes' => array('class' => array('clearfix')),
  );

  $form['video_filter']['file_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Video URL'),
    '#maxlength' => 255,
    '#size' => 80,
    '#default_value' => '',
    '#weight' => 1,
  );

  $form['video_filter']['width'] = array(
    '#type' => 'textfield',
    '#title' => t('Width'),
    '#maxlength' => 255,
    '#size' => 80,
    '#default_value' => '',
    '#weight' => 2,
  );

  $form['video_filter']['height'] = array(
    '#type' => 'textfield',
    '#title' => t('Height'),
    '#maxlength' => 255,
    '#size' => 80,
    '#default_value' => '',
    '#weight' => 3,
  );

  $form['video_filter']['align'] = array(
    '#type' => 'select',
    '#title' => t('Align'),
    '#default_value' => 'none',
    '#options' => array(
      'none' => t('None'),
      'left' => t('Left'),
      'right' => t('Right'),
      'center' => t('Center'),
    ),
    '#weight' => 4,
  );

  $form['instructions'] = array(
    '#type' => 'fieldset',
    '#title' => t('Instructions'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#attributes' => array('class' => array('clearfix')),
    '#weight' => 97,
  );

  $text = '<p>' . t('Insert a 3rd party video from one of the following providers.') . '</p>';
  $text .= _video_filter_instructions();

  $form['instructions']['text'] = array(
    '#type' => 'item',
    '#markup' => $text,
  );

  $form['cancel'] = array(
    '#type' => 'button',
    '#value' => t('Cancel'),
    '#weight' => 98,
  );

  $form['insert'] = array(
    '#type' => 'button',
    '#value' => t('Insert'),
    '#weight' => 99,
  );

  return $form;
}

function video_filter_wysiwyg_plugin($editor, $version) {
  _video_filter_add_settings('wysiwyg_' . $editor);

  $plugins = array();

  switch ($editor) {
    case 'ckeditor':
      $plugins['video_filter'] = array(
        'path' => drupal_get_path('module', 'video_filter') . '/editors/ckeditor/',
        'buttons' => array('video_filter' => t('Video filter')),
        'url' => 'http://drupal.org/project/video_filter',
        'load' => TRUE,
      );
      break;

    case 'fckeditor':
      $plugins['video_filter'] = array(
        'path' => drupal_get_path('module', 'video_filter') . '/editors/fckeditor/',
        'buttons' => array('video_filter' => t('Video filter')),
        'url' => 'http://drupal.org/project/video_filter',
        'load' => TRUE,
      );
      break;

    case 'tinymce':
      $plugins['video_filter'] = array(
        'path' => drupal_get_path('module', 'video_filter') . '/editors/tinymce',
        'filename' => 'editor_plugin.js',
        'buttons' => array('video_filter' => t('Video filter')),
        'url' => 'http://drupal.org/project/video_filter',
        'load' => TRUE,
      );
      break;
  }

  return $plugins;
}

/**
 * Implements hook_element_info_alter().
 */
function video_filter_element_info_alter(&$types) {
  if (isset($types['text_format']['#pre_render']) && is_array($types['text_format']['#pre_render'])) {
    if (in_array('ckeditor_pre_render_text_format', $types['text_format']['#pre_render'])) {
      _video_filter_add_settings('ckeditor');
    }
  }
}

/*
 * 根据用户提交的(swf/html)地址，获取优酷，土豆的swf播放地址
 * */
function _getSwf ($url = '') {
    if(isset($url) && !empty($url)){
        preg_match_all('/http:\/\/(.*?)?\.(.*?)?\.com\/(.*)/',$url,$types);
    }else{
        return false;
    }
    $type = $types[2][0];
    $domain = $types[1][0];
    $isswf = strpos($types[3][0], 'v.swf') === false ? false : true;
    $method = substr($types[3][0],0,1);

    switch ($type){
        case 'youku' :
            if( $domain == 'player' ) {
                $swf = $url;
            }else if( $domain == 'v' ) {
                preg_match_all('/http:\/\/v\.youku\.com\/v_show\/id_(.*)?\.html/',$url,$url_array);
                $swf = 'http://player.youku.com/player.php/sid/'.str_replace('/','',$url_array[1][0]).'/v.swf';
            }else{
                $swf = $url;
            }
            break;
        case 'tudou' :
            if($isswf){
                $swf = $url;
            }else{
                $method = $method == 'p' ? 'v' : $method ;
                preg_match_all('/http:\/\/www.tudou\.com\/(.*)?\/(.*)?/',$url,$url_array);
                $str_arr = explode('/',$url_array[1][0]);
                $count = count($str_arr);
                if($count == 1) {
                    $id = explode('.',$url_array[2][0])[0];
                }else if($count == 2){
                    $id = $str_arr[1];
                }else if($count == 3){
                    $id = $str_arr[2];
                }
                $swf = 'http://www.tudou.com/'.$method.'/'.$id.'/v.swf';
            }
            break;
        default :
            $swf = $url;
            break;
    }
    return $swf;
}


function _video_filter_add_settings($editor) {
  static $editor_settings_added = array();
  static $global_settings_added = FALSE;

  if (!isset($editor_settings_added[$editor])) {
    $editor_settings_added[$editor] = TRUE;

    // Add popup url.
    $settings = array(
      'video_filter' => array('url' => array($editor => url('video_filter/dashboard/' . $editor))),
    );
    drupal_add_js($settings, 'setting');
  }

  if (!$global_settings_added) {
    $global_settings_added = TRUE;

    // Add global settings for video_filter.
    $settings = array(
      'video_filter' => array(
        'modulepath' => drupal_get_path('module', 'video_filter'),
      ),
    );
    drupal_add_js($settings, 'setting');
  }
}

/**
 * Parses Codec into instructions for WYSIWYG popup.
 */
function _video_filter_instructions() {
  $codecs = video_filter_get_codec_info();
  $output = '<ul>';
  foreach ($codecs as $codec) {
    $output .= '<li><strong>' . $codec['name'] . '</strong><br />' . $codec['sample_url'] . '</li>';
  }
  $output .= '</ul>';
  return $output;
}

/**
 * Requests data from an oEmbed provider.
 *
 * Note: This function currently only supports JSON responses.
 *
 * @param string $endpoint
 *   The provider endpoint URL.
 * @param array $arguments
 *   An associative array of URL arguments to send the provider.
 *
 * @return array|FALSE
 *   An array of data if the request is successful, otherwise FALSE.
 *
 * @todo Support other response formats than JSON?
 */
function video_filter_oembed_request($endpoint, array $arguments) {
  // Make HTTP request.
  $result = drupal_http_request(url($endpoint, array('query' => $arguments)));

  if ($data = json_decode($result->data)) {
    // Success.
    return (array) $data;
  }
  else {
    // Failure. Either the resource doesn't exist or there was an error with the
    // request.
    return FALSE;
  }
}
